
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  doc: [
    'README',
    { 
      type: 'category',
      label: 'Hostované služby',
      //link: { type: 'doc', id: 'hosting' },
      collapsed: false,
      collapsible: false,
      items: [
        { type: 'autogenerated', dirName: 'hosting' }
      ]
    },
    {
      type: 'category',
      label: 'Ostatní služby',
      collapsed: false,
      collapsible: false,
      items: [
        'brightid-verifikace',
      ]
    },
    {
      type: 'category',
      label: 'Dokumentace',
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: 'link',
          label: 'DeFi Toolkit',
          href: 'https://hackmd.io/@gweicz/defi-toolkit'
        },
        {
          type: 'link',
          label: 'DAO Příručka',
          href: 'https://dao.gwei.cz/'
        },
      ]
    },
  ],
};

module.exports = sidebars;
