
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  doc: [
    'README',
    { 
      type: 'category',
      label: 'Hostované služby',
      link: { type: 'doc', id: 'hosting' },
      items: [
        { type: 'autogenerated', dirName: 'hosting' }
      ]
    },
    {
      type: 'category',
      label: 'Ostatní služby',
      items: [
        'brightid-verifikace',
      ]
    },
    {
      type: 'category',
      label: 'Události',
      items: [
        'ethbrno',
        'utxoprague',
        'palime-ether'
      ]
    },
    {
      type: 'category',
      label: 'Dokumentace',
      items: [
        'defi-toolkit',
        'dao-prirucka'
      ]
    },
    {
      type: 'category',
      label: 'Iniciativy',
      items: [
        'bohemiandao',
        'utxo-foundation',
        'dczk'
      ]
    },
  ],
};

module.exports = sidebars;
