/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  doc: [
    'README',
    'klicove-pojmy',
    {
      type: 'category',
      label: 'Komunikační kanály',
      link: { type: 'doc', id: 'komunikacni-kanaly/README' },
      items: [
        'komunikacni-kanaly/forum',
        'komunikacni-kanaly/matrix',
        'komunikacni-kanaly/mastodon',
        //'komunikacni-kanaly/blog',
        'komunikacni-kanaly/twitter',
        'komunikacni-kanaly/discord',
      ],
    },
    'nastroje',
    {
      type: 'category',
      label: 'Council',
      link: { type: 'doc', id: 'council/README' },
      items: [
        'council/clenove',
        'council/pokladna',
        {
          type: 'category',
          label: 'Governance Call',
          link: { type: 'doc', id: 'council/governance-call/README' },
          items: [
            'council/governance-call/seznam-setkani',
          ],
        },
      ],
    },
    'historie',
    'media-kit',
    'partneri',
    {
      type: 'category',
      label: 'Podpořte nás',
      link: { type: 'doc', id: 'podporte-nas/README' },
      items: [
        'podporte-nas/aktivni-ucast',
        'podporte-nas/financni-podpora',
        'podporte-nas/gitcoin-grants',
      ],
    },
  ],
};

module.exports = sidebars;
